// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX05FoIC5S4LlaMLNAm_o0L_16UhOIJVs',
    appId: '1:34646014386:web:c4b373bc722757b1f48cab',
    messagingSenderId: '34646014386',
    projectId: 'futsal-37be1',
    authDomain: 'futsal-37be1.firebaseapp.com',
    storageBucket: 'futsal-37be1.firebasestorage.app',
    measurementId: 'G-VPSZVVK5Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzNlsfnyQmzlOY_tWT8kMn0WO_vz6glM',
    appId: '1:34646014386:android:f1ed91ab923cb40cf48cab',
    messagingSenderId: '34646014386',
    projectId: 'futsal-37be1',
    storageBucket: 'futsal-37be1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-S86jDji6V3pRLMbSLBSn1nzBXSGik8',
    appId: '1:34646014386:ios:82fb21dc5ba4b871f48cab',
    messagingSenderId: '34646014386',
    projectId: 'futsal-37be1',
    storageBucket: 'futsal-37be1.firebasestorage.app',
    iosBundleId: 'com.example.futsal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-S86jDji6V3pRLMbSLBSn1nzBXSGik8',
    appId: '1:34646014386:ios:82fb21dc5ba4b871f48cab',
    messagingSenderId: '34646014386',
    projectId: 'futsal-37be1',
    storageBucket: 'futsal-37be1.firebasestorage.app',
    iosBundleId: 'com.example.futsal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX05FoIC5S4LlaMLNAm_o0L_16UhOIJVs',
    appId: '1:34646014386:web:1d409057f7b466c7f48cab',
    messagingSenderId: '34646014386',
    projectId: 'futsal-37be1',
    authDomain: 'futsal-37be1.firebaseapp.com',
    storageBucket: 'futsal-37be1.firebasestorage.app',
    measurementId: 'G-WY507NTJX1',
  );
}
